#!/bin/bash

set -euo pipefail

if ! command -v chezmoi >/dev/null; then
    sh -c "$(curl -fsLS get.chezmoi.io)" -- init --apply git@github.com:dembasiby/dotfiles.git
fi

echo "set -o vi" >> ~/.bashrc

exit 0
